### ISSUE TITLE
Error 400 on upload

### ISSUE THREAD

**Issue by ChadBailey** [trmcnvn/chrome-addon#6]
Hello, I'm a collaborator for https://github.com/igrigorik/videospeed and we're experiencing an error 400 when running this action. I believe it worked without issue in the past, so not sure what I may be doing wrong.

Here is a detailed bug report in our own repo for your reference https://github.com/igrigorik/videospeed/issues/614

I suspect the issue may be related to one of these fields being incorrect

```yaml
      client-id: ${{ secrets.CHROME_CLIENT_ID }}
      client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
```

However, I really can't validate since I'm not the product owner so I don't have access to these secrets. I don't mind having the owner validate, which is what my next step will probably be. Still I'm submitting this report so that future internet goers with the same problem could find this as a clue to their problem.

Error 400 (I assume http status code for bad request) is pretty ambiguous. I'm sure that's likely just the upstream error received. If this is due to invalid client secrets, perhaps the error 400 could be trapped and a friendly error message could be presented informing the user to check their client-id/secret/token.
